In [2]:
import lightgbm as lgb
from sklearn.metrics import roc_auc_score
import pandas as pd
import numpy as np

data = "/mnt/d/Data/mangaki-data-challenge/latest/"
train = pd.read_csv(data+'train_0.csv')
test = pd.read_csv(data+'test_0.csv')

params = {
    'task': 'train',
    'boosting_type': 'rf',
    'objective': 'binary',
    'metric': {'auc'},
    'num_leaves': 450,
    'min_data_in_leaf': 8,
    'feature_fraction': 0.6,
    'bagging_fraction': 0.8,
    'bagging_freq': 1,
    'lambda_l1': 0,
    'min_gain_to_split': 0,
    'verbose': 0
}

In [3]:
params = {
    'task': 'train',
    'boosting_type': 'gbdt',
    'objective': 'binary',
    'metric': {'auc'},
    'num_leaves': 60,
    'min_data_in_leaf': 60,
    'feature_fraction': 0.6,
    'bagging_fraction': 0.96,
    'bagging_freq': 1,
    'lambda_l1': 0,
    'verbose': 0
}

In [4]:
X = lgb.Dataset(train.drop(['user_id', 'work_id', 'rating'], axis=1), train['rating'])
gbdt = lgb.train(params, X, num_boost_round=142, valid_sets=[X], verbose_eval=True)
Y = gbdt.predict(test.drop(['user_id', 'work_id'], axis=1))

[1]	training's auc: 0.764878
[2]	training's auc: 0.804899
[3]	training's auc: 0.819501
[4]	training's auc: 0.830656
[5]	training's auc: 0.833657
[6]	training's auc: 0.842414
[7]	training's auc: 0.847715
[8]	training's auc: 0.851276
[9]	training's auc: 0.856444
[10]	training's auc: 0.860661
[11]	training's auc: 0.864061
[12]	training's auc: 0.868097
[13]	training's auc: 0.872097
[14]	training's auc: 0.877377
[15]	training's auc: 0.881081
[16]	training's auc: 0.884323
[17]	training's auc: 0.888547
[18]	training's auc: 0.891383
[19]	training's auc: 0.894178
[20]	training's auc: 0.896842
[21]	training's auc: 0.899678
[22]	training's auc: 0.901846
[23]	training's auc: 0.90475
[24]	training's auc: 0.907068
[25]	training's auc: 0.910249
[26]	training's auc: 0.912402
[27]	training's auc: 0.915018
[28]	training's auc: 0.917068
[29]	training's auc: 0.918972
[30]	training's auc: 0.920938
[31]	training's auc: 0.923179
[32]	training's auc: 0.924769
[33]	training's auc: 0.926708
[34]	training's auc:

In [3]:
# fm training
from scipy.sparse import hstack
from fastFM import sgd
from sklearn.metrics import roc_auc_score
from sklearn.datasets import load_svmlight_file

path = "/mnt/d/Data/mangaki-data-challenge/libfm/"

params = {
    'n_iter':300000, 
    'init_stdev':0.01,
    'l2_reg_w':0.0001,
    'l2_reg_V':0.5,
    'rank':1,
    'step_size':0.02
}

train, ty = load_svmlight_file(path+"train_0.csv", zero_based=True)
test, _ = load_svmlight_file(path+"test_0.csv")
fm = sgd.FMClassification(**params)
fm.fit(train, np.require(ty*2-1, dtype=np.int))
Y = fm.predict_proba(test)

In [5]:
test = pd.read_csv(data+'../test.csv', dtype={
    'user_id': np.int16,
    'work_id': np.int16
})
#test['prob_willsee'] = (pgbdt*0.804944+prf*0.802744)/(0.802744+0.804944)
test['prob_willsee'] = Y

In [6]:
pgbdt=Y

In [3]:
prf=Y

In [7]:
test.to_csv(data+"../result_09_15_01.csv", index=False)

In [6]:
Y

array([ 0.36552496,  0.84494495,  0.33360538, ...,  0.80084167,
        0.90624881,  0.53616675])

In [9]:
pt = pd.read_csv(data+"../libfm/test_result.csv", header=None, names=['prob_willsee'])

In [11]:
test['prob_willsee']=pt

In [16]:
(fm.predict_proba(test)>0.99).sum()

92698

In [20]:
_

array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

In [30]:
train

<11112x11891 sparse matrix of type '<class 'numpy.float64'>'
	with 146128 stored elements in Compressed Sparse Row format>

In [31]:
test

<100015x11892 sparse matrix of type '<class 'numpy.float64'>'
	with 1315262 stored elements in Compressed Sparse Row format>

In [23]:
test[0,:].data

array([ 1.        ,  1.        ,  0.72826087,  0.15217391,  2.60869565,
        0.17366651,  0.27941176,  0.2254902 ,  0.00980392,  0.48529412,
        1.96568627,  0.18466436])

In [28]:
test[0,:].indptr

array([ 0, 12], dtype=int32)

In [25]:
train[0, :].data

array([ 1.        ,  1.        ,  0.39189189,  0.39189189,  0.04054054,
        0.17567568,  0.52027027,  0.97582781,  0.07478632,  0.70299145,
        0.04273504,  0.17948718,  0.6784188 ,  0.66357103])